### PR TITLE
fixed and updated README | badges, grammer & co.

### LINKED ISSUE #5: Add Go build tag to the README
Can we please add the state of the current build status badge to GitHub README?

### PR DESCRIPTION
**Pull request by daily-fred**
Hello, it's me again.

I have improved the `README.md` further and especially adjusted the badges and thus also closed #5 actually. 

I commented [here](https://github.com/aurae-runtime/ae/issues/5#issuecomment-1437173232) and thought I'd open a pull request right away.

The changed things are as follows:

* The colours of the badges adjusted, depending on the brand identity.
* Added build badge for go-releaser, will be linked to [here](https://github.com/aurae-runtime/ae/actions/workflows/090-go-release-ubuntu-latest-go-releaser.yaml).
* I also fixed a few grammatical errors and misspelled words.

**See it in action: [HERE](https://github.com/daily-fred/ae/blob/readme-update/README.md)**

---

I would appreciate feedback, maybe one person to look over it briefly.

I also wanted to briefly address what I wrote in the comment:

> I also wanted to ask if [Go Cover](https://gocover.io/) (would be a GitHub Action) and [Go Report Card](https://goreportcard.com/) would be worth a badge?

_Fred_

### CODE REVIEW

**Comment by dmah42** [comment]
looks like the CI bots aren't happy with some indenting in the README (the editorconfig checks). can you fix those please?

**Comment by daily-fred** [comment]
> looks like the CI bots aren't happy with some indenting in the README (the editorconfig checks). can you fix those please?

Will look into it, was also a problem last time. Is it possible to check it ahead of time? I will try to check it out. Cheers!

**Comment by dmah42** [comment]
> > looks like the CI bots aren't happy with some indenting in the README (the editorconfig checks). can you fix those please?
> 
> Will look into it, was also a problem last time. Is it possible to check it ahead of time? I will try to check it out. Cheers!

i think if you're using an editor that supports [editorconfig](https://editorconfig.org/) then your editor should automatically format things as per the configuration in the project.

**Comment by daily-fred** [comment]
Worked out the padding problem, just gonna fix the error with the HTML spoilers and blank lines.

**Comment by daily-fred** [comment]
LGTM! You can take a look [here](https://github.com/daily-fred/ae/blob/readme-update/README.md).

**Review by dmah42 — APPROVED** [review]

**Comment by dmah42** [comment]
thanks!

**Pull request merged**
